TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += brnkhrst.db
DATA += brnkhrst.proto

#=======================================
include $(TOP)/configure/RULES
